/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tela;
import Personagens.*;
import Strategy.*;
import java.util.Random;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class TelaJogo extends javax.swing.JFrame {
    Personagens guerreiro = new Personagens("Guerreiro", 200, 10, 5);
    Personagens mago = new Personagens("Mago", 100, 5, 15);
    Personagens arqueiro = new Personagens("Arqueiro", 150, 15, 10);
    Personagens boss = new Personagens("BOSS", 1000, 20, 15);
    int cout = 3;
    int count = 1;
    boolean flag = true;
    ArrayList<String> nomes = new ArrayList<String>();
    String saida = "";
    /**
     * Creates new form TelaJogo
     */
    public TelaJogo() {
        initComponents();
        attTela();
        nomes.add("Guerreiro");
        nomes.add("Mago");
        nomes.add("Arqueiro");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxP1 = new javax.swing.JComboBox<>();
        jComboBoxP2 = new javax.swing.JComboBox<>();
        jComboBoxP3 = new javax.swing.JComboBox<>();
        jLabelPersonagem1 = new javax.swing.JLabel();
        jLabelPersonagem2 = new javax.swing.JLabel();
        jLabelPersonagem3 = new javax.swing.JLabel();
        jTextFieldBossVida = new javax.swing.JTextField();
        jLabelBoss = new javax.swing.JLabel();
        jButtonConfirmar = new javax.swing.JButton();
        jTextFieldVida1 = new javax.swing.JTextField();
        jTextFieldVida2 = new javax.swing.JTextField();
        jTextFieldVida3 = new javax.swing.JTextField();
        jLabelFundo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RPG");
        setMaximizedBounds(new java.awt.Rectangle(1000, 1000, 1000, 1000));
        setMaximumSize(new java.awt.Dimension(900, 900));
        setMinimumSize(new java.awt.Dimension(1000, 750));
        setResizable(false);
        setSize(new java.awt.Dimension(950, 950));
        getContentPane().setLayout(null);

        jComboBoxP1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxP1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBoxP1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxP1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ataque Fraco", "Ataque Forte", "Curar" }));
        getContentPane().add(jComboBoxP1);
        jComboBoxP1.setBounds(350, 290, 150, 27);

        jComboBoxP2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxP2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBoxP2.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxP2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ataque Fraco", "Ataque Forte", "Curar" }));
        getContentPane().add(jComboBoxP2);
        jComboBoxP2.setBounds(180, 360, 150, 27);

        jComboBoxP3.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxP3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBoxP3.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxP3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ataque Fraco", "Ataque Forte", "Curar" }));
        jComboBoxP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxP3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxP3);
        jComboBoxP3.setBounds(180, 160, 150, 27);

        jLabelPersonagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cavaleiro.png"))); // NOI18N
        getContentPane().add(jLabelPersonagem1);
        jLabelPersonagem1.setBounds(190, 250, 220, 100);

        jLabelPersonagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mago.png"))); // NOI18N
        getContentPane().add(jLabelPersonagem2);
        jLabelPersonagem2.setBounds(80, 320, 100, 110);

        jLabelPersonagem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/arqueiro.png"))); // NOI18N
        getContentPane().add(jLabelPersonagem3);
        jLabelPersonagem3.setBounds(80, 130, 100, 110);

        jTextFieldBossVida.setEditable(false);
        jTextFieldBossVida.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldBossVida.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldBossVida);
        jTextFieldBossVida.setBounds(690, 80, 110, 30);

        jLabelBoss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/boss_updated (1).png"))); // NOI18N
        getContentPane().add(jLabelBoss);
        jLabelBoss.setBounds(500, 40, 520, 390);

        jButtonConfirmar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonConfirmar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonConfirmar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmar);
        jButtonConfirmar.setBounds(360, 20, 140, 60);

        jTextFieldVida1.setEditable(false);
        jTextFieldVida1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVida1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldVida1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextFieldVida1);
        jTextFieldVida1.setBounds(270, 220, 80, 30);

        jTextFieldVida2.setEditable(false);
        jTextFieldVida2.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVida2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldVida2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextFieldVida2);
        jTextFieldVida2.setBounds(80, 290, 80, 27);

        jTextFieldVida3.setEditable(false);
        jTextFieldVida3.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVida3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldVida3.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextFieldVida3);
        jTextFieldVida3.setBounds(80, 100, 80, 27);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/OIG.jpg"))); // NOI18N
        jLabelFundo.setMaximumSize(new java.awt.Dimension(1024, 1024));
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 1024, 482);

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 481, 1030, 230);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1030, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxP3ActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        // TODO add your handling code here:
        try {
            saida += "Rodada"+count+":\n";
            if(guerreiro.vivo()){
                execucao((String)(jComboBoxP1.getSelectedItem()),guerreiro);
            }
            if(mago.vivo()){
                execucao((String)(jComboBoxP2.getSelectedItem()),mago);
            }
            if(arqueiro.vivo()){
                execucao((String)(jComboBoxP3.getSelectedItem()),arqueiro);
            }
            padraoBoss();
            attTela();
            jTextArea1.setText(saida);
            count++;
        } catch (Exception e) {
            attTela();
            jTextArea1.setText(saida);
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }  
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    public void attTela(){
        jTextFieldBossVida.setText(boss.getVida()+"/1000");
        jTextFieldVida1.setText(guerreiro.getVida()+"/200");
        jTextFieldVida2.setText(mago.getVida()+"/100");
        jTextFieldVida3.setText(arqueiro.getVida()+"/150");
    }
    public void padraoBoss()throws Exception{
        if(cout == 0) throw new Exception("O Boss Venceu!");
        Random aleatorio = new Random(); 
        int dano = 0;
        int escolha = aleatorio.nextInt(cout);
        int tipo = aleatorio.nextInt(2) + 1;
        
        if(tipo == 1) boss.escolherAcao(new AtaqueFraco());
        if(tipo == 2) boss.escolherAcao(new  AtaqueForte());
        dano = boss.executarAcao();
        
        switch (nomes.get(escolha)) {
            case "Guerreiro":                
                guerreiro.setVida(guerreiro.getVida()-dano);
                saida += "O boss atacou o Guerreiro";
                if (dano == 0){
                    saida += ",errou o ataque\n";
                }else{
                    saida += ",causando "+dano+"\n";
                }
                if(guerreiro.vivo() == false){
                    nomes.remove(escolha);
                    cout--;
                    saida += "O Guerreiro morreu !\n";
                    jLabelPersonagem1.setVisible(false);
                    jComboBoxP1.setVisible(false);
                    jTextFieldVida1.setVisible(false);
                }
                break;
            case "Mago":
                mago.setVida(mago.getVida()-dano);
                saida += "O boss atacou o Mago";
                if (dano == 0){
                    saida += ",errou o ataque\n";
                }else{
                    saida += ",causando "+dano+"\n";
                }
                if(mago.vivo() == false){
                    nomes.remove(escolha);
                    cout--;
                    saida += "O Mago morreu !\n";
                    jLabelPersonagem2.setVisible(false);
                    jComboBoxP2.setVisible(false);
                    jTextFieldVida2.setVisible(false);
                }
                break;
            case "Arqueiro":
                arqueiro.setVida(arqueiro.getVida()-dano);
                saida += "O boss atacou o Arqueiro";
                if (dano == 0){
                    saida += ",errou o ataque\n";
                }else{
                    saida += ",causando "+dano+"\n";
                }
                if(arqueiro.vivo() == false){
                    nomes.remove(escolha);
                    cout--;
                    saida += "O Arqueiro morreu !\n";
                    jLabelPersonagem3.setVisible(false);
                    jComboBoxP3.setVisible(false);
                    jTextFieldVida3.setVisible(false);
                }
                break;
            default:
                throw new AssertionError();
        }
        if(cout == 0) throw new Exception("O Boss Venceu!");
    }
    public void execucao(String op, Personagens personagem)throws Exception{
        if("Ataque Fraco".equals(op)){
            personagem.escolherAcao(new AtaqueFraco());
            int dano = personagem.executarAcao();
            boss.setVida(boss.getVida()-dano);
            if(dano == 0){
                saida += personagem.getNome() + " Errou o ataque\n";
            }else{
                saida += personagem.getNome() + " realizou um ataque fraco, causando "+ dano+"\n";
            }
            
            if(boss.vivo() == false) throw new Exception("Parabens Você venceu!");
        }
        if("Ataque Forte".equals(op)){
            personagem.escolherAcao(new AtaqueForte());
            int dano = personagem.executarAcao();
            boss.setVida(boss.getVida()-dano);
            if(dano == 0){
                saida += personagem.getNome() + " Errou o ataque\n";
            }else{
                saida += personagem.getNome() + " realizou um ataque forte, causando "+ dano+"\n";
            }
            if(boss.vivo() == false) throw new Exception("Parabens Você venceu!");
        }
        if("Curar".equals(op)){
            personagem.escolherAcao(new Curar());
            int cura = personagem.executarAcao();
            personagem.setVida(personagem.getVida()+cura); 
            saida += personagem.getNome() + " se curou em "+ cura+"\n";
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JComboBox<String> jComboBoxP1;
    private javax.swing.JComboBox<String> jComboBoxP2;
    private javax.swing.JComboBox<String> jComboBoxP3;
    private javax.swing.JLabel jLabelBoss;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelPersonagem1;
    private javax.swing.JLabel jLabelPersonagem2;
    private javax.swing.JLabel jLabelPersonagem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldBossVida;
    private javax.swing.JTextField jTextFieldVida1;
    private javax.swing.JTextField jTextFieldVida2;
    private javax.swing.JTextField jTextFieldVida3;
    // End of variables declaration//GEN-END:variables
}
